INSERT INTO modules
(slug, module_type, display_number, title, image_url, video_url, time_label, duration_label, focus_json, key_question, content_text, reflection_prompt, sort_order, is_active)
VALUES
('introduction', 'Introduction', 'i', 'Platform Tour', 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80', 'videos/demo-introduction.mp4', '5 minutes', '5:00', JSON_ARRAY('What the learner sees', 'How course navigation works', 'Where progress is tracked'), 'What should a buyer understand in the first two minutes of this LMS demo?', '## Welcome to LMS DEMO\nThis introduction gives a quick tour of the learner experience.\n\n## What this demo shows\n- A branded learner portal\n- Lesson navigation\n- Video playback and resume support\n- Profile and total video progress', 'What part of the learner experience would matter most to your buyer?', 10, 1),
('module-1', 'Lesson 1', '1', 'Learner Onboarding', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80', 'videos/demo-module-1.mp4', '8 minutes', '8:00', JSON_ARRAY('Account access', 'Course dashboard', 'Learner profile', 'First-session expectations'), 'How quickly can a new learner understand what to do next?', '## Lesson 1 Introduction\nThis lesson demonstrates the onboarding flow.\n\n## What to point out\n- Clean login and account state\n- Profile details\n- Total video progress\n- Clear next step navigation', 'Where would you customize onboarding copy for a real client?', 20, 1),
('module-2', 'Lesson 2', '2', 'Course Content Experience', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80', 'videos/demo-module-2.mp4', '9 minutes', '9:00', JSON_ARRAY('Lesson pages', 'Video placement', 'Learning focus', 'Key questions'), 'Does each lesson make the next learner action obvious?', '## Lesson 2 Introduction\nThis lesson explains the content layout used across the LMS.\n\n## Demo talking points\n- Videos can be uploaded locally or hosted externally\n- Written content supports buyers who need more than video\n- Focus lists make lessons scannable', 'What type of course content would be easiest to sell with this layout?', 30, 1),
('module-3', 'Lesson 3', '3', 'Progress Tracking', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', 'videos/demo-module-3.mp4', '7 minutes', '7:00', JSON_ARRAY('Per-video progress', 'Resume playback', 'Overall watched percentage', 'Admin reporting'), 'What proof of learning progress does the buyer need?', '## Lesson 3 Introduction\nThis lesson focuses on progress tracking.\n\n## Why it matters\n- Learners can resume where they left off\n- Admins can monitor engagement\n- Sales demos can show measurable course activity', 'Which progress metric would help close a buyer conversation?', 40, 1),
('module-4', 'Lesson 4', '4', 'Admin and Content Control', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80', 'videos/demo-module-4.mp4', '10 minutes', '10:00', JSON_ARRAY('Lesson editing', 'Learner approvals', 'Resources', 'Comment moderation'), 'How much control should the client team have without calling a developer?', '## Lesson 4 Introduction\nThis lesson prepares you to show the admin side.\n\n## What to demonstrate\n- Edit course titles and text\n- Approve or reject learners\n- Add downloadable resources\n- Review learner comments', 'Which admin feature should be shown first in a live sales demo?', 50, 1),
('module-5', 'Lesson 5', '5', 'Launch Checklist', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80', 'videos/demo-module-5.mp4', '6 minutes', '6:00', JSON_ARRAY('Branding', 'Videos', 'Learners', 'Resources', 'Go-live review'), 'What has to be changed before this demo becomes a client-ready LMS?', '## Lesson 5 Introduction\nThis final lesson turns the demo into a practical checklist.\n\n## Client-ready checklist\n- Replace LMS DEMO branding with the client brand\n- Upload final videos\n- Rewrite lesson content\n- Create learner groups', 'What is the first customization you would make for a new buyer?', 60, 1);

INSERT INTO resources (title, file_url, file_name, file_type, sort_order)
VALUES
('Demo Setup Checklist', '#', 'demo-setup-checklist.pdf', 'pdf', 10),
('Buyer Walkthrough Script', '#', 'buyer-walkthrough-script.pdf', 'pdf', 20),
('Admin Feature Summary', '#', 'admin-feature-summary.pdf', 'pdf', 30),
('Launch Readiness Worksheet', '#', 'launch-readiness-worksheet.pdf', 'pdf', 40);


